Docker ver
Haruki-Kny/PaletteCloud_tutorial1 pull request #2
Opened 2022-02-17 06:54 UTC by Haruki-Kny

2022-02-17 07:54 UTC, nanoGimlet requested changes

2022-02-17 07:54 UTC, nanoGimlet commented on Gemfile
> +<<<<<<< HEAD
コンフリクト起きた時のやつなので消して大丈夫です

2022-02-17 07:54 UTC, nanoGimlet commented on Gemfile
> +=======
同様に消して大丈夫です

2022-02-17 07:54 UTC, nanoGimlet commented on Gemfile
> +>>>>>>> 096d738f90fb5ff72e854d96929f504987523563
同様に消して大丈夫です

2022-02-17 07:54 UTC, nanoGimlet commented on config/database.yml
> +<<<<<<< HEAD
同様に消して大丈夫です

2022-02-17 07:54 UTC, nanoGimlet commented on docker-compose.yml
> +      LAND: C.UTF-8
これLANG（language）です。
参考資料の方直しておきます。すみません...

2022-02-17 07:55 UTC, gonzaemon111 approved these changes

2022-02-17 07:55 UTC, gonzaemon111 commented on Gemfile
> +>>>>>>> 096d738f90fb5ff72e854d96929f504987523563
これだめですね！

2022-02-17 07:55 UTC, gonzaemon111 commented on Gemfile
> +>>>>>>> 096d738f90fb5ff72e854d96929f504987523563
これgitでconflictされてますね

2022-02-17 07:56 UTC, gonzaemon111 commented
これconflictを解消したら、mergeしちゃっていいですよ

2022-02-18 03:51 UTC, Haruki-Kny commented on Gemfile
> +<<<<<<< HEAD
全部直したつもりだったんですが、残ってました...

2022-02-18 03:56 UTC, merged